AI_ALGORITHMS_LOCAL_RUN = "AI_ALGORITHMS_LOCAL_RUN"
ALGO_CONTAINER_NAME = "ALGO_CONTAINER_NAME"
CURRENT_HOST = "CURRENT_HOST"
DEV_DSK = "DEV_DSK"
ENABLE_PROFILER = "ENABLE_PROFILER"
HOSTS = "HOSTS"
MAX_CONTENT_LENGTH = "MAX_CONTENT_LENGTH"
SAGEMAKER_BATCH = "SAGEMAKER_BATCH"
SAGEMAKER_DATA_PATH = "SAGEMAKER_DATA_PATH"
SCHEDULER_PORT = "SCHEDULER_PORT"
SAGEMAKER_INFERENCE_ACCELERATOR_PRESENT = "SAGEMAKER_INFERENCE_ACCELERATOR_PRESENT"
NUM_WORKERS = 'NUM_WORKERS'
SAGEMAKER_BIND_TO_PORT = "SAGEMAKER_BIND_TO_PORT"
SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT = "SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT"

# Custom environment variables defined for Strategia
MODEL_METADATA_DYNAMO_TABLE = "MODEL_METADATA_DYNAMO_TABLE"
EXP_METADATA_DYNAMO_TABLE = "EXP_METADATA_DYNAMO_TABLE"
MODEL_METADATA_POLLING = "MODEL_METADATA_POLLING"
EXPERIMENT_ID = "EXPERIMENT_ID"
MODEL_ID = "MODEL_ID"
LOG_INFERENCE_DATA = "LOG_INFERENCE_DATA"
KINESIS_QUEUE = "KINESIS_QUEUE"
FIREHOSE_STREAM = "FIREHOSE_STREAM"
FIREHOSE_BUFFER_ON = "FIREHOSE_BUFFER_ON"

# Type of weights store
S3_REF = "S3REF"  # Weights are stored in S3
INPLACE = "INPLACE"  # Weights are stored in the ModelDB metadata table itself (for small weights)

PIDFILE = "/tmp/gunicorn_pid"